export enum Role {
    ROLE_MANAGER = 'ROLE_MANAGER',
    ROLE_OPERATOR = 'ROLE_OPERATOR',
    ROLE_DATA = 'ROLE_DATA',

    ROLE_SERVER_REST_ACCESS = 'ROLE_SERVER_REST_ACCESS',
    ROLE_ASSET_REST_ACCESS = 'ROLE_ASSET_REST_ACCESS',
    ROLE_BILLING = 'ROLE_BILLING',

    ROLE_MASTER_ADMIN = 'ROLE_MASTER_ADMIN',
    ROLE_MASTER_OPERATOR = 'ROLE_MASTER_OPERATOR',
    ROLE_MASTER_SUPPORT = 'ROLE_MASTER_SUPPORT',
    ROLE_MASTER_ASSET_MANAGER = 'ROLE_MASTER_ASSET_MANAGER',

    ROLE_ADMIN = 'ROLE_ADMIN',

    // --

    Manager = 'ROLE_MANAGER',
    Operator = 'ROLE_OPERATOR',
    Data = 'ROLE_DATA',

    ServerrestAccess = 'ROLE_SERVER_REST_ACCESS',
    AssetRestAccess = 'ROLE_ASSET_REST_ACCESS',
    Billing = 'ROLE_BILLING',

    MasterAdmin = 'ROLE_MASTER_ADMIN',
    MasterOpertator = 'ROLE_MASTER_OPERATOR',
    MasterSupport = 'ROLE_MASTER_SUPPORT',
    MasterAssetManager = 'ROLE_MASTER_ASSET_MANAGER',

    Admin = 'ROLE_ADMIN'

}