export interface SimpleApi {
    id: number;
    name: string;
    code: string;
    params: string;
    scheme: string;
}

/*
CREATE table mhbp_api
(
    ID              bigint generated by default as identity (start with 1) PRIMARY KEY,
    VERSION         NUMERIC(10, 0) NOT NULL,
    COMPANY_ID      NUMERIC(10, 0) NOT NULL,
    ACCOUNT_ID      NUMERIC(10, 0) NOT NULL,
    CREATED_ON      bigint         NOT NULL,
    NAME            VARCHAR(250)   NOT NULL,
    CODE            VARCHAR(50)    NOT NULL,
    DISABLED        BOOLEAN not null default false,
    PARAMS          TEXT           not null,
    MODEL           TEXT           not null
);
*/